### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deep0learning** [dribnet/kerosene#13]
I am getting the following error. Can you help to fix the error please?

Traceback (most recent call last):
  File "mnist.py", line 6, in <module>
    from kerosene.datasets import mnist
  File "/home/DL/keras_capsn_virtual/local/lib/python2.7/site-packages/kerosene/datasets/mnist.py", line 3, in <module>
    from .dataset import Dataset
  File "/home/DL/keras_capsn_virtual/local/lib/python2.7/site-packages/kerosene/datasets/dataset.py", line 11, in <module>
    initial_fuel_config_path = fuel.config.data_path
  File "/home/DL/keras_capsn_virtual/local/lib/python2.7/site-packages/fuel/config_parser.py", line 150, in __getattr__
    "provided: {}.".format(key))
fuel.exceptions.ConfigurationError: Configuration not set and no default provided: data_path.

**Comment by heitorrapela** [comment]
import os
DATASETS_FOLDER = 'datasets'
if not os.path.isdir(DATASETS_FOLDER):
       os.mkdir(DATASETS_FOLDER)
os.environ['FUEL_DATA_PATH']='./datasets/'
from kerosene.datasets import mnist
