### ISSUE TITLE
SVHN Model Exception

### ISSUE THREAD

**Issue by rajankarthiks** [dribnet/kerosene#6]
When I try to run the SVHN example I am getting an Exception 'ValueError: Negative dimension size caused by subtracting 2 from 1'

`Traceback (most recent call last):
  File "kerosen.py", line 63, in <module>
    model.add(MaxPooling2D(pool_size=(2, 2)))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/models.py", line 325, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/topology.py", line 516, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/topology.py", line 570, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/topology.py", line 154, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/layers/pooling.py", line 160, in call
    dim_ordering=self.dim_ordering)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/layers/pooling.py", line 210, in _pooling_function
    border_mode, dim_ordering, pool_mode='max')
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/backend/tensorflow_backend.py", line 1809, in pool2d
    x = tf.nn.max_pool(x, pool_size, strides, padding=padding)
  File "/home/karthik/tensorflow_py2/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 850, in max_pool
    name=name)
  File "/home/karthik/tensorflow_py2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1440, in _max_pool
    data_format=data_format, name=name)
  File "/home/karthik/tensorflow_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/karthik/tensorflow_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/home/karthik/tensorflow_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/karthik/tensorflow_py2/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1
`

Could you please help me out?

**Comment by dribnet** [comment]
Hi - sorry for the delay. I see you are running Keras 1.1.1 and this was last tested on 0.3.0. If you'd like to still use this, I can try refreshing the code examples in the repo to work with the latest version.

**Comment by dribnet** [comment]
This was done in #9, so I'm going to close this issue.
