### ISSUE TITLE
Error at example cifar10.py  

### ISSUE THREAD

**Issue by HunterHantao** [dribnet/kerosene#7]
Below is the error message.  Please help. 

Using TensorFlow backend.
Traceback (most recent call last):
  File "cifar10.py", line 39, in <module>
    (X_train, y_train), (X_test, y_test) = cifar10.load_data()
  File "/home/kowalski/python/anaconda3/lib/python3.5/site-packages/kerosene/datasets/dataset.py", line 47, in <lambda>
    return map(lambda x: fuel_data_to_list(x, shuffle=shuffle), fuel_datasets)
  File "/home/kowalski/python/anaconda3/lib/python3.5/site-packages/kerosene/datasets/dataset.py", line 43, in fuel_data_to_list
    return fuel_data_stream.get_epoch_iterator().next()   
AttributeError: 'DataIterator' object has no attribute 'next'

**Comment by HunterHantao** [comment]
I figure this out. This is due to my python version 3.5.2. .next() is changed to 

> __next__() 
http://stackoverflow.com/questions/12274606/theres-no-next-function-in-a-yield-generator-in-python-3
